### ISSUE TITLE
MathJax support consideration

### ISSUE THREAD

**Issue by andrewcrook** [alemayhu/2anki.net#209]
I see you use the Katex from HTML, however, are you aware that MathJax is built into Anki?
MathJax can also render Latex.

It's benefits are: 

- no external services
- no extra JS libraries required 
- it is supported in Anki mobile and desktop versions
- **Can be edited simply by the user in Anki without going into HTML**
- mobile Anki can also render and be edited on the mobile device.

To use this you would have to do remove KaTex from the cards and change the suffix and prefix accordingly. 

`this is a test for inline  \( 1 \times 2 \)  and this is a test of a block  \[ 2 \times 2[\] and this is an example of chemistery   \(\ce{H2O}\)`

Desktop
<img width="614" alt="image" src="https://user-images.githubusercontent.com/803618/97777615-641bed80-1b69-11eb-8da0-8151bc79f074.png">

I think you would have to forget the chemistry option.

I wonder if it would be beneficial for users to have this as a conversion option?

**Comment by aalemayhu** [comment]
Hei Andrew!

Yes, I have seen it mentioned in the manual. I will look into this in a few weeks.
If you need this working earlier, feel free to contribute changes 🙂

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
Twitch: http://twitch.tv/alemayhu <http://twitch.tv/alemayhu>

**Comment by aalemayhu** [comment]
Note for later https://docs.ankiweb.net/math.html
