### ISSUE TITLE
Cherry Picking picks up a toggle nesting it though it doesn't have cherry.

### ISSUE THREAD

**Issue by dummifiedme** [alemayhu/2anki.net#217]
The Notion Screenshot. Note that the 'Hey' must not be included in the cards as it's not cherry-picked.
![image](https://user-images.githubusercontent.com/68785729/99073890-c39fe180-25dc-11eb-9421-ff7ce13be85c.png)

The cards imported into the ANKI. The card 'Hey' is imported when it's not supposed to.
![image](https://user-images.githubusercontent.com/68785729/99073963-e8945480-25dc-11eb-9778-0e682bb01040.png)

If I am missing something, please let me know :) 
Thanks :)

**Comment by aalemayhu** [comment]
The current is weird, yes. I agree and we will address this in the future, thanks!

**Comment by aalemayhu** [comment]
This is actually resolved by using the following card options, you can also check out this YouTube video [Maximum One Toggle per Card | Notion to Anki Tutorial - Card Option](https://youtu.be/DiYc5UErYOY).

- [ ] Maximum One Toggle Per Card
- [ ] Use All Toggle
