### ISSUE TITLE
Support both front and back image flashcards

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/2anki.net#471]
This came out from conversation on Discord. Currently Notion has restrictions on the toggle, so it's not possible to add images to the front in their implementation. 

One alternative is to use columns where it's possible to have two columns and the front / back can be column 1 / 2.

**Comment by aalemayhu** [comment]
<img width="525" alt="Screenshot 2022-02-04 at 11 44 36 AM" src="https://user-images.githubusercontent.com/925044/152515847-ffe300ea-9e4a-4c7c-bf15-da36c25cf1ab.png">

**Comment by PeterKeffer** [comment]
Are you using a simple table for this? (Not a Notion Pro) Because there I can't add images to tables cells.

**Comment by aalemayhu** [comment]
I have Notion pro account but let me try to do it in a regular account.

**Comment by PeterKeffer** [comment]
I also have a Pro Account - probably I'm doing something wrong?

**Comment by aalemayhu** [comment]
You can drag things around to position them in columns. There are block types for columns and column but they get created when you drag things, see this page https://www.notion.so/help/columns-headings-and-dividers
