### ISSUE TITLE
Clicking collapsed Navbar icon opens options and immediately redirects to page.

### ISSUE THREAD

**Issue by aloutfi** [alemayhu/2anki.net#529]
**Describe the bug**
At a width below 1024 pixels, the navbar is collapsed into the 2anki icon. When the icon is pressed, it opens the nav options, and then immediately redirects to 2anki.net

**To Reproduce**
1. Set width to below 1024 pixels
2. click on the 2anki icon at the top left of the screen.
3. the options open, the page redirects.

**Expected behavior**
Navbar options are displayed without redirect.

**Screenshots**
https://user-images.githubusercontent.com/63522731/160951684-22d7f1ab-926b-4a81-8969-3bf6426ac306.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.3
 - Browser brave-browser-nightly (chromium)
 - Version 
    - browser: V1.37.109
    - chromium: 100.0.4896.60

**Additional context**
The new site looks great! 🎉 You've put a lot of work into this project and has helped a lot of people. 🙂

**Comment by aalemayhu** [comment]
Thanks for reporting this. It has been fixed.
